### ISSUE TITLE
Synthesizer

### ISSUE THREAD

**Issue by gktval** [accordion-mega/AccordionMega#3]
Awesome project! Thank you so much. This has inspired me to create my own. Think I'll try to do it with an MSP430 instead of Arduino, though. 

Question: Have you found a synthesizer with various accordion sounds? I was thinking about adding buttons for the registers, but would like to find a program with a library that can support them. For example a clarinet, musette, master, etc.

**Comment by accordion-mega** [comment]
wow. thanks. it was way old to reproduce it with arduino again ;) sadly they don't make (or i've not found good one) accordion samples, mostly because of keyboard usage, so it looks like accordion but completely without breath. playing roland, they won ;)
